import { Metadata } from "next";
import Client from "./page.client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home = () => {
  return <Client />
};

export default Home;
